- name: DevOps Setup Demo
  hosts: localhost
  connection: local
  become: yes

  tasks:

    - name: Update system
      apt:
        update_cache: yes

    - name: Install curl
      apt:
        name: curl
        state: present

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Start Docker
      service:
        name: docker
        state: started

    - name: Check Kubernetes files exist
      command: ls