name: Full DevOps Pipeline

on:
  push:
    branches: [ "main", "feature-ui" ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Build Docker Image
      run: docker build -t weather-app .

    - name: Test Application
      run: echo "Test Passed"

    - name: Run Container
      run: docker run -d -p 8080:80 weather-app

    - name: Kubernetes Deploy (Simulated)
      run: echo "kubectl apply -f deployment.yaml"